# Generated by Django 3.2.9 on 2021-11-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_dagree',
            field=models.CharField(default='user', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
