# Generated by Django 3.2.9 on 2021-11-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211122_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertificats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_id', models.CharField(default='', max_length=255)),
                ('ser_fayl_id', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
