# Generated by Django 3.2.9 on 2021-11-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sertificats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sertificats',
            name='ser_id',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
